name: Simple Shutdown Tracker CI/CD

on:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the code
        run: |
          python main.py build

  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - name: Checkouting code
        uses: actions/checkout@v3

      - name: Zipping code
        run: |
          git archive --format zip --output powerbot.zip main

      - name: Transferring zip to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: powerbot.zip
          target: /home/ubuntu/

      - name: Installing ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding server to known hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Executing deployment script on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            sudo chmod -R 755 /home/ubuntu/powerbot.zip
            unzip -o /home/ubuntu/powerbot.zip -d powerbot
            rm -rf /home/ubuntu/powerbot.zip 
            sudo touch /home/ubuntu/powerbot/.env
            echo "${{ secrets.BOT_TOKEN }}" > /home/ubuntu/powerbot/.env
            cd powerbot
            sudo docker compose up -d --build
            echo "Deployment pipeline successfully finished and cleanup complete"
